### ISSUE TITLE
拼多多抓包需要登录怎么解决？

### ISSUE THREAD

**Issue by xuqiuye** [OFZFZS/scrapy-pinduoduo#4]

**Comment by OFZFZS** [comment]
那就登录自己的账号抓包啊，需要实现拼多多批量登录 批量注册也有方法

**Comment by xuqiuye** [comment]
拼多多支持微信，QQ和手机号码登录。如果是手机批量登录，怎么获取验证码？

**Comment by OFZFZS** [comment]
> 拼多多支持微信，QQ和手机号码登录。如果是手机批量登录，怎么获取验证码？

打码平台，一毛钱一条

**Comment by jieopeng** [comment]
> > 拼多多支持微信，QQ和手机号码登录。如果是手机批量登录，怎么获取验证码？
> 
> 打码平台，一毛钱一条

请问有合适的平台可以推荐吗

**Comment by xuqiuye** [comment]
已解决
